import type { Trainer } from "./types";

export const trainers: Trainer[] = [
  {
    id: "vikram",
    name: "Vikram Rathore",
    role: "Head coach",
    specialisation: "Powerlifting & Olympic lifts",
    certifications: ["NASM-CPT", "K11 Level 2", "ACE-CPT"],
    years: 11,
    philosophy: "If the bar path is ugly, the ego is louder than the work.",
  },
  {
    id: "ananya",
    name: "Ananya Sharma",
    role: "Mobility lead",
    specialisation: "Yoga & hip restoration",
    certifications: ["ACE Health Coach", "K11 Yoga"],
    years: 8,
    philosophy: "Strong hips keep Jaipur knees in the game past 40.",
  },
  {
    id: "rohan",
    name: "Rohan Meena",
    role: "Engineer of the WOD",
    specialisation: "CrossFit programming",
    certifications: ["NASM-CPT", "K11 Strength"],
    years: 7,
    philosophy: "Scale the load. Don't scale the honesty.",
  },
  {
    id: "priya",
    name: "Priya Khandelwal",
    role: "Conditioning",
    specialisation: "HIIT & sled work",
    certifications: ["ACE-CPT", "NASM-CPT"],
    years: 6,
    philosophy: "Your engine is built on days you wanted to skip the bike.",
  },
  {
    id: "imran",
    name: "Imran Khan",
    role: "Combat",
    specialisation: "MMA fundamentals",
    certifications: ["K11 Combat", "ACE-CPT"],
    years: 9,
    philosophy: "Pad work first. Sparring is a privilege you earn with control.",
  },
  {
    id: "sneha",
    name: "Sneha Joshi",
    role: "Rhythm floor",
    specialisation: "Zumba & group energy",
    certifications: ["ACE Group Fitness", "K11"],
    years: 5,
    philosophy: "If you can laugh and still hit the beat, you will come back tomorrow.",
  },
];
